version: '2'

services:
  pub:
    networks:
      - psubnet
    build:
      context: ./pub
      dockerfile: Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
    restart: unless-stopped

  sub:
    networks:
      - psubnet
    build:
      context: ./sub
      dockerfile: Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
    ports:
      - "1920:3000"
    restart: unless-stopped

  nats:
    image: nats
    networks:
      - psubnet
    ports:
      - "1919:4222"
    restart: unless-stopped

networks:
  psubnet:
    driver: bridge